apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        log
        cache 30
        kubernetes cluster.local {
           fallthrough
        }
        edge ${MY_IP} ${LON} ${LAT} . ${UPSTREAMS} ${DEBUG_LEVELS}
        proxy . 8.8.8.8:53
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
