apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        log
        cache 30
        kubernetes cluster.local {
           fallthrough
        }
        edge ${MY_IP} ${LON} ${LAT} . ${CENTRAL_IP}:53 {
            svc_read_interval ${SVC_READ_INTERVAL}s
            svc_push_interval ${SVC_PUSH_INTERVAL}s
        }
        proxy . 8.8.8.8:53
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
