kind: PersistentVolume
apiVersion: v1
metadata:
  name: optikon-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/optikon"
